server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://106.12.37.43:3306/firecontrol?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8
    username: root
    password: BEWATER@07121128
    driver-class-name: com.mysql.cj.jdbc.Driver
    minIdle: 5
    maxActive: 100
    initialSize: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    removeAbandoned: true
    filters: stat # ,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
    druidLoginName: wjf # 登录druid的账号
    druidPassword: wjf # 登录druid的密码
    cachePrepStmts: true # 开启二级缓存

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  rabbitmq:
    host: 106.12.37.43
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true  #确认消息已发送到交换机(Exchange)
    publisher-returns: true  #确认消息已发送到队列(Queue)


mybatis:
   mapperLocations: classpath:/mapper/*/*.xml
#   别名
   typeAliasesPackage: com.orient.firecontrol_web_demo.model
#   包扫描
   mapperScanPackage: com.orient.firecontrol_web_demo.dao


logging:
  level:
    com.orient.firecontrol_web_demo: debug #com.orient.server包下所有class以debug级别输出 控制台打印sql语句（debug级别才可以）

pagehelper:
    params: count=countSql
    # 指定分页插件使用哪种方言
    helper-dialect: mysql
    # 分页合理化参数 pageNum<=0时会查询第一页 pageNum>pages(超过总数时) 会查询最后一页
    reasonable: 'true'
    support-methods-arguments: 'true'




